feat: add comments and refactor FIFO queue
rustsbi/prototyper pull request #29
Opened 2024-11-18 02:14 UTC by chenzongyao200127

This PR focuses on enhancing code clarity and improving the logic of the FIFO (First In First Out) queue.

Changes:
- Added comments to clarify the purpose and functionality of the code.  
- Refactored the FIFO queue to make the implementation more straightforward.

2024-11-18 02:38 UTC, woshiluo commented on prototyper/src/sbi/console.rs
> +        let _ = self.write_char(c as u8 as char);
Why remove unwrap here?

2024-11-18 02:53 UTC, chenzongyao200127 commented on prototyper/src/sbi/console.rs
> +        let _ = self.write_char(c as u8 as char);
Sorry, it was my mistake

2024-11-18 03:37 UTC, woshiluo approved these changes

2024-11-18 03:37 UTC, woshiluo commented
LGTM

2024-11-18 04:49 UTC, luojia65 requested changes
Please apply some changes on documentation.

2024-11-18 04:49 UTC, luojia65 commented on prototyper/src/dt.rs
> +/// Root device tree structure containing system information
```suggestion
/// Root device tree structure containing system information.
```

All the documentation comments should include a period (`.`) at the end of a sentence. Ref: https://doc.rust-lang.org/stable/std/io/index.html#structs

2024-11-18 04:49 UTC, luojia65 commented on prototyper/src/main.rs
> +        // 3. Init SBI implementation
```suggestion
        // 3. Init the SBI implementation
```

2024-11-18 04:49 UTC, luojia65 commented on prototyper/src/sbi/rfence.rs
> +    pub start_addr: usize, // Start address of memory region to fence
```suggestion
    /// Start address of memory region to fence
    pub start_addr: usize,
```

2024-11-18 04:59 UTC, chenzongyao200127 commented on prototyper/src/dt.rs
> +/// Root device tree structure containing system information
Thanks for the feedback! You're absolutely right, including a period at the end of sentences in documentation comments aligns with Rust's style guide. I'll update the comments accordingly.

2024-11-18 06:13 UTC, chenzongyao200127 commented on prototyper/src/main.rs
> +        // 3. Init SBI implementation
Got it, I'll fix this. Thanks for pointing it out!

2024-11-18 06:13 UTC, chenzongyao200127 commented on prototyper/src/sbi/rfence.rs
> +    pub start_addr: usize, // Start address of memory region to fence
Fixed! Please let me know if there’s anything else:)

2024-11-18 08:30 UTC, luojia65 requested changes

2024-11-18 08:30 UTC, luojia65 commented on prototyper/src/riscv_spec.rs
> +pub const CSR_STIMECMP: u32 = 0x14D; // Supervisor timer compare value
```suggestion
/// Time value (lower 32 bits).
pub const CSR_TIME: u32 = 0xc01;
/// Time value (upper 32 bits).
pub const CSR_TIMEH: u32 = 0xc81;
/// Supervisor timer compare value.
pub const CSR_STIMECMP: u32 = 0x14D;
```

2024-11-18 08:30 UTC, luojia65 commented on prototyper/src/main.rs
> +    // Track whether SBI is initialized and ready
```suggestion
    // Track whether SBI is initialized and ready.
```
Please add periods for internal comments as well for clear writing format.

2024-11-18 08:30 UTC, luojia65 commented on prototyper/src/platform/dynamic.rs
> +/// Returns Result containing DynamicInfo or error details.
```suggestion
/// Reads dynamic info from physical address.
///
/// Returns a `Result` containing `DynamicInfo` or error details.
```
Rustdoc follows markdown format, meaning an empty line should be inserted between every two paragraphs. We prefer to include Rust structures, enumerations, traits and variables in code blocks.

2024-11-18 08:30 UTC, luojia65 commented on prototyper/src/platform/dynamic.rs
> +/// Returns Result containing tuple of (MPP, next_addr) or error details.
```suggestion
/// Validates and extracts privilege mode and next address from dynamic info.
///
/// Returns `Result` containing tuple of `(MPP, next_addr)` or error details.
```

2024-11-18 08:30 UTC, luojia65 commented on prototyper/src/riscv_spec.rs
> +            // Read current menvcfg value
```suggestion
            // Read current `menvcfg` value.
```

2024-11-18 08:30 UTC, luojia65 commented on prototyper/src/sbi/console.rs
> +    /// Returns 0 on success.
Please evaluate if those two sentences should be put into one paragraph; if so, try to concat two short sentences into one line. Or, if not, please insert a new empty line between them.

2024-11-18 08:30 UTC, luojia65 commented on prototyper/src/sbi/fifo.rs
> +    pub fn new() -> Self {
```suggestion
    #[inline]
    pub fn new() -> Self {
```

2024-11-18 08:30 UTC, luojia65 commented on prototyper/src/sbi/hsm.rs
> +    /// Caller must ensure this cell belongs to the current hart.
```suggestion
    ///
    /// Caller must ensure this cell belongs to the current hart.
```

2024-11-18 08:30 UTC, luojia65 commented on prototyper/src/sbi/hsm.rs
> +    /// Returns inner data if successful, otherwise returns current state.
```suggestion
    /// Attempts to transition hart from START_PENDING to STARTED state.
    ///
    /// Returns inner data if successful, otherwise returns current state.
```

2024-11-18 08:30 UTC, luojia65 commented on prototyper/src/sbi/logger.rs
>      fn flush(&self) {}
```suggestion
    // No-op flush since we use println! which is already line-buffered
    #[inline]
    fn flush(&self) {}
```

2024-11-18 09:56 UTC, chenzongyao200127 commented on prototyper/src/sbi/console.rs
> +    /// Returns 0 on success.
Good catch! I'll update the code. Thanks for the feedback.

2024-11-19 07:27 UTC, chenzongyao200127 commented on prototyper/src/sbi/hsm.rs
> +    /// Returns inner data if successful, otherwise returns current state.
Thanks for the suggestion! I've addressed it in the latest commit:)

2024-11-19 07:29 UTC, chenzongyao200127 commented on prototyper/src/riscv_spec.rs
> +pub const CSR_STIMECMP: u32 = 0x14D; // Supervisor timer compare value
Thanks for the suggestion! I've addressed it.

2024-11-19 10:07 UTC, luojia65 commented
@chenzongyao200127 : Please squash the commits.

2024-11-20 01:33 UTC, chenzongyao200127 commented
> @chenzongyao200127 : Please squash the commits.

No ploblem, after last night's discussion, there are still issues with the rfence memory order access points, and I am continuing to make adjustments:)

2024-11-20 05:21 UTC, woshiluo commented on prototyper/src/sbi/ipi.rs
> +        if let Some(local) = rfence::local_rfence() {
Shall we ignore this none?

2024-11-21 06:57 UTC, chenzongyao200127 commented on prototyper/src/sbi/ipi.rs
> +        if let Some(local) = rfence::local_rfence() {
Got it!

2024-11-21 07:08 UTC, luojia65 approved these changes
LGTM

2024-11-21 11:45 UTC, guttatus commented on prototyper/src/sbi/rfence.rs
> -    HFenceVvma,
`sbi_remote_hfence_vvma` is a standard function defined in SBI and should not be deleted

2024-11-21 12:08 UTC, guttatus commented on prototyper/src/sbi/console.rs
> +        .expect("Console not initialized")
If console not  initialized, we can not use `except`.

2024-11-21 12:08 UTC, guttatus commented on prototyper/src/sbi/console.rs
> +        .expect("Console not initialized")
If console not  initialized, we can not use `except`.

2024-11-21 12:25 UTC, chenzongyao200127 commented on prototyper/src/sbi/trap_stack.rs
> +            .expect("Failed to create trap stack")
Thank you for pointing that out! You're correct, I have fixed this in the current revision. Appreciate your feedback!

2024-11-22 06:28 UTC, merged